disabled_rules:
  - line_length
  - force_try
  - force_cast
  - function_body_length
  - type_body_length
  - file_length
  - nesting
  - identifier_name
  - cyclomatic_complexity
  - type_name
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_string
  - explicit_init
  - redundant_nil_coalescing
  - implicitly_unwrapped_optional

included:
  - Sources
  - Tests

excluded:
  - Sources/RepoBar/API/Generated

analyzer_rules:
  - unused_declaration
  - unused_import

reporter: "xcode"
